export const themeOptions = [
	{ value: '#277c78', label: 'Green' },
	{ value: '#f2cdac', label: 'Yellow' },
	{ value: '#82c9d7', label: 'Cyan' },
	{ value: '#626070', label: 'Navy' },
	{ value: '#c94736', label: 'Red' },
	{ value: '#826cb0', label: 'Purple' },
	{ value: '#af81ba', label: 'Lavender' },
	{ value: '#597c7c', label: 'Teal' },
	{ value: '#93674f', label: 'Brown' },
	{ value: '#934f6f', label: 'Magenta' },
	{ value: '#3f82b2', label: 'Blue' },
	{ value: '#7f9161', label: 'Olive' },
	{ value: '#cab361', label: 'Gold' },
	{ value: '#be6c49', label: 'Orange' },
]
